
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'jaffle_shop'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"] # for seeds
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table

# Table:
# Data is stored on disk
# Slower to build
# Faster to query
# Configure in dbt_project.yml or with the following config block

# View:
# Query is stored on disk
# Faster to build
# Slower to query
# Configure in dbt_project.yml or with the following config block

# Ephemeral:
# Does not exist in the database, can not query directly
# Imported as CTE into downstream models
# Increases build time of downstream models
# Configure in dbt_project.yml or with the following config block

# Increment
# Built as table in the database
# On the first run, builds entire table
# On subsequent runs, only appends new records
# Faster to build because you are only adding new records
# Does not capture 100% of the data all the time

# Snapshots
# Built as a table in the database, usually in a dedicated schema.
# On the first run, builds entire table and adds four columns: dbt_scd_id, dbt_updated_at, dbt_valid_from, and dbt_valid_to
